export const movies = [
    {
      "adult": false,
      "backdrop_path": "/5hoS3nEkGGXUfmnu39yw1k52JX5.jpg",
      "genre_ids": [28, 12, 14],
      "id": 960704,
      "original_language": "ja",
      "original_title": "鋼の錬金術師 完結編 最後の錬成",
      "overview": "The Elric brothers’ long and winding journey comes to a close in this epic finale, where they must face off against an unworldly, nationwide threat.",
      "popularity": 4030.287,
      "poster_path": "/AeyiuQUUs78bPkz18FY3AzNFF8b.jpg",
      "release_date": "2022-06-24",
      "title": "Fullmetal Alchemist: The Final Alchemy",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 47
    },
    {
      "adult": false,
      "backdrop_path": "/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg",
      "genre_ids": [27, 53],
      "id": 760161,
      "original_language": "en",
      "original_title": "Orphan: First Kill",
      "overview": "After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",
      "popularity": 3744.732,
      "poster_path": "/pHkKbIRoCe7zIFvqan9LFSaQAde.jpg",
      "release_date": "2022-07-27",
      "title": "Orphan: First Kill",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 964
    },
    {
      "adult": false,
      "backdrop_path": "/iS9U3VHpPEjTWnwmW56CrBlpgLj.jpg",
      "genre_ids": [14, 35, 10751],
      "id": 642885,
      "original_language": "en",
      "original_title": "Hocus Pocus 2",
      "overview": "It’s been 29 years since someone lit the Black Flame Candle and resurrected the 17th-century sisters, and they are looking for revenge. Now it is up to three high-school students to stop the ravenous witches from wreaking a new kind of havoc on Salem before dawn on All Hallow’s Eve.",
      "popularity": 3389.879,
      "poster_path": "/7ze7YNmUaX81ufctGqt0AgHxRtL.jpg",
      "release_date": "2022-09-27",
      "title": "Hocus Pocus 2",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 648
    },
    {
      "adult": false,
      "backdrop_path": "/hT3OqvzMqCQuJsUjZnQwA5NuxgK.jpg",
      "genre_ids": [53],
      "id": 985939,
      "original_language": "en",
      "original_title": "Fall",
      "overview": "For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights",
      "popularity": 3302.231,
      "poster_path": "/spCAxD99U1A6jsiePFoqdEcY0dG.jpg",
      "release_date": "2022-08-11",
      "title": "Fall",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 1363
    },
    {
      "adult": false,
      "backdrop_path": "/aIkG2V4UXrfkxMdJZmq30xO0QQr.jpg",
      "genre_ids": [878, 12, 28],
      "id": 791155,
      "original_language": "en",
      "original_title": "Secret Headquarters",
      "overview": "While hanging out after school, Charlie and his friends discover the headquarters of the world’s most powerful superhero hidden beneath his home. When villains attack, they must team up to defend the headquarters and save the world.",
      "popularity": 3117.231,
      "poster_path": "/8PsHogUfvjWPGdWAI5uslDhHDx7.jpg",
      "release_date": "2022-08-12",
      "title": "Secret Headquarters",
      "video": false,
      "vote_average": 7,
      "vote_count": 81
    },
    {
      "adult": false,
      "backdrop_path": "/83oeqwN64WtafGoITvsOzjKIQaM.jpg",
      "genre_ids": [28, 35, 53],
      "id": 718930,
      "original_language": "en",
      "original_title": "Bullet Train",
      "overview": "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
      "popularity": 3103.725,
      "poster_path": "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
      "release_date": "2022-07-03",
      "title": "Bullet Train",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 1680
    },
    {
      "adult": false,
      "backdrop_path": "/ghsPsvM0sEztdNT4kUlTsBF2LEF.jpg",
      "genre_ids": [18, 28, 53],
      "id": 852046,
      "original_language": "fr",
      "original_title": "Athena",
      "overview": "Hours after the tragic death of their youngest brother in unexplained circumstances, three siblings have their lives thrown into chaos.",
      "popularity": 2780.156,
      "poster_path": "/fenNPxVF5ERy0CSyVruuEg959Hg.jpg",
      "release_date": "2022-09-09",
      "title": "Athena",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 250
    },
    {
      "adult": false,
      "backdrop_path": "/7AiIrnDMaOhPrw9elJ5NNjijTW4.jpg",
      "genre_ids": [53, 9648],
      "id": 916605,
      "original_language": "en",
      "original_title": "The Infernal Machine",
      "overview": "Reclusive and controversial author Bruce Cogburn is drawn out of hiding by an obsessive fan, forcing the novelist to confront a past that he thought he could escape, and to account for events set in motion by his bestseller decades earlier. Cogburn's search for who is behind the manipulation and mental torment he encounters leads to an emotional roller-coaster ride full of fear and danger, where things are not always as clear as they seem to be, and where past deeds can have dire consequences.",
      "popularity": 2508.595,
      "poster_path": "/bSqpOGzaKBdGkBLmcm1JJIVryYy.jpg",
      "release_date": "2022-09-23",
      "title": "The Infernal Machine",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 65
    },
    {
      "adult": false,
      "backdrop_path": "/rgZ3hdzgMgYgzvBfwNEVW01bpK1.jpg",
      "genre_ids": [28, 53, 18],
      "id": 429473,
      "original_language": "en",
      "original_title": "Lou",
      "overview": "A young girl is kidnapped during a powerful storm. Her mother joins forces with her mysterious neighbour to set off in pursuit of the kidnapper. Their journey will test their limits and expose the dark secrets of their past.",
      "popularity": 1945.623,
      "poster_path": "/djM2s4wSaATn4jVB33cV05PEbV7.jpg",
      "release_date": "2022-09-23",
      "title": "Lou",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 243
    },
    {
      "adult": false,
      "backdrop_path": "/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg",
      "genre_ids": [14, 12, 10751],
      "id": 532639,
      "original_language": "en",
      "original_title": "Pinocchio",
      "overview": "A wooden puppet embarks on a thrilling adventure to become a real boy.",
      "popularity": 1908.354,
      "poster_path": "/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg",
      "release_date": "2022-09-07",
      "title": "Pinocchio",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 891
    }
  ]